name: CS16MC
version: '${project.version}'
main: pe.bazan.luis.plugins.cs16mc.CS16MC
authors:
  - Luis Bazan
api-version: '1.20'
depend: [ Multiverse-Core ]
commands:
  cs16mc:
    permission: cs16mc.commands
    description: Main command of the plugin CS16MC
    usage: /cs16mc help
